apiVersion: apps/v1
kind: Deployment
metadata:
  name: apparel-shop
  labels:
    app: shopping
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: kart-webserver
        image: nginx
