apiVersion: apps/v1
kind: Deployment
metadata:
  name: apparel-shop-blue
  labels:
    app: shopping-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shop-blue
  template:
    metadata:
      labels:
        app: shop-blue
    spec:
      containers:
      - name: blue-webserver
        image: jdevasia/web:blue
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apparel-shop-green
  labels:
    app: shopping
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shop-green
  template:
    metadata:
      labels:
        app: shop-green
    spec:
      containers:
      - name: green-webserver
        image: jdevasia/web:green
